{{- if .Values.hosts.livekit }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: livekit-server
  namespace: stoatchat-livekit
  labels:
    app.kubernetes.io/name: livekit-server
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.tls.issuer }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "haproxy" }}
  rules:
    - host: livekit.{{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: livekit-livekit-server
                port:
                  number: 80
  tls:
    - hosts:
        - livekit.{{ .Values.domain }}
      secretName: livekit-tls
{{- end }}
